sequenceDiagram
    participant PC
    participant GoProBLE
    participant GoProWiFi
    loop Steps from Connect Tutorial
        GoProBLE-->>PC: Advertising
        GoProBLE-->>PC: Advertising
        note over PC: Scanning
        PC->>GoProBLE: Connect
        note over GoProBLE, PC: Connected
        alt If not Previously Paired
            PC ->> GoProBLE: Pair Request
            GoProBLE ->> PC: Pair Response
        else

        end
        note over GoProBLE, PC: Paired
        PC ->> GoProBLE: Enable Notifications on Characteristic 1
        PC ->> GoProBLE: Enable Notifications on Characteristic 2
        PC ->> GoProBLE: Enable Notifications on Characteristic ..
        PC ->> GoProBLE: Enable Notifications on Characteristic N
        note over GoProBLE, PC: Ready to Communicate
    end
    PC ->> GoProBLE: Read Wifi AP SSID
    PC ->> GoProBLE: Read Wifi AP Password
    PC ->> GoProBLE: Write to Enable WiFi AP
    GoProBLE ->> PC: Response sent as notification
    note over GoProWiFi: WiFi AP enabled
    PC ->> GoProWiFi: Connect to WiFi AP