"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
*
Defines the structure of protobuf messages for querying camera capabilities
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
from . import response_generic_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RequestGetCameraCapabilities(google.protobuf.message.Message):
    """*
    Get the camera capabilities

    Returns a @ref ResponseGetCameraCapabilities
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None: ...

global___RequestGetCameraCapabilities = RequestGetCameraCapabilities

@typing_extensions.final
class ResponseGetCameraCapabilities(google.protobuf.message.Message):
    """*
    Camera Capabilities

    Message is sent in response to a @ref RequestGetCameraCapabilities.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    SCHEMA_VERSION_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    result: response_generic_pb2.EnumResultGeneric.ValueType
    "Generic pass/fail/error info"
    schema_version: builtins.str
    'Capability schema version (e.g., "camera-capabilities/v1.0")'

    @property
    def protocol(self) -> global___ProtocolCapabilities:
        """Protocol-level capabilities"""

    def __init__(
        self,
        *,
        result: response_generic_pb2.EnumResultGeneric.ValueType | None = ...,
        schema_version: builtins.str | None = ...,
        protocol: global___ProtocolCapabilities | None = ...
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "protocol", b"protocol", "result", b"result", "schema_version", b"schema_version"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "protocol", b"protocol", "result", b"result", "schema_version", b"schema_version"
        ],
    ) -> None: ...

global___ResponseGetCameraCapabilities = ResponseGetCameraCapabilities

@typing_extensions.final
class ProtocolCapabilities(google.protobuf.message.Message):
    """*
    Protocol capability information
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUPPORTS_2BYTE_IDS_FIELD_NUMBER: builtins.int
    supports_2byte_ids: builtins.bool
    "Does the camera support 2-byte setting/status IDs"

    def __init__(self, *, supports_2byte_ids: builtins.bool | None = ...) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["supports_2byte_ids", b"supports_2byte_ids"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["supports_2byte_ids", b"supports_2byte_ids"]
    ) -> None: ...

global___ProtocolCapabilities = ProtocolCapabilities
