"\n@generated by mypy-protobuf.  Do not edit manually!\nisort:skip_file\n*\nCommands to query and manipulate media files\n"
import builtins
import google.protobuf.descriptor
import google.protobuf.message
from . import response_generic_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RequestGetLastCapturedMedia(google.protobuf.message.Message):
    "*\n    Get the last captured media filename\n\n    Returns a @ref ResponseLastCapturedMedia\n"
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None: ...

global___RequestGetLastCapturedMedia = RequestGetLastCapturedMedia

@typing_extensions.final
class ResponseLastCapturedMedia(google.protobuf.message.Message):
    "*\n    The Last Captured Media\n\n    Message is sent in response to a @ref RequestGetLastCapturedMedia.\n\n    This contains the relative path of the last captured media starting from the `DCIM` directory on the SDCard. Depending\n    on the type of media captured, it will return:\n\n    - The single media path for single photo/video media\n    - The path to the first captured media in the group for grouped media\n"
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    MEDIA_FIELD_NUMBER: builtins.int
    result: response_generic_pb2.EnumResultGeneric.ValueType
    "Was the request successful?"

    @property
    def media(self) -> response_generic_pb2.Media:
        "*\n        Last captured media if result is RESULT_SUCCESS. Invalid if result is RESULT_RESOURCE_NOT_AVAILBLE.\n"

    def __init__(
        self,
        *,
        result: response_generic_pb2.EnumResultGeneric.ValueType | None = ...,
        media: response_generic_pb2.Media | None = ...
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal[("media", b"media", "result", b"result")]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[("media", b"media", "result", b"result")]) -> None: ...

global___ResponseLastCapturedMedia = ResponseLastCapturedMedia
