# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: set_camera_control_status.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class EnumCameraControlStatus(betterproto.Enum):
    CAMERA_IDLE = 0
    CAMERA_CONTROL = 1
    CAMERA_EXTERNAL_CONTROL = 2


@dataclass
class RequestSetCameraControlStatus(betterproto.Message):
    camera_control_status: "EnumCameraControlStatus" = betterproto.enum_field(1)
