# turbo_transfer_pb.py/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).
# This copyright was auto-generated on Wed, Sep  1, 2021  5:05:49 PM

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: turbo_transfer.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RequestSetTurboActive(betterproto.Message):
    active: bool = betterproto.bool_field(1)
