name: Check for Secrets (Non-docs)

# This is only intended to be run from the internal repo.

on:
    workflow_dispatch:
    pull_request:

jobs:
    checkSecrets:
        name: Check for Leaked Secrets
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source branch
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup the secretchecker image
              run: docker pull ghcr.io/gopro/opengopro-staging/gpdocchecker:docs

            - name: Check for secrets
              run: MSYS_NO_PATHCONV=1 docker run --volume .:/docs ghcr.io/gopro/opengopro-staging/gpdocchecker:docs secretchecker

            - name: Write failure report
              if: failure()
              run: |
                  ls -la
                  cat ./report.md
                  cat ./report.md > $GITHUB_STEP_SUMMARY
