name: Check for Secrets

# This is only intended to be run from the internal repo.

on:
    pull_request:

jobs:
    checkSecrets:
        name: Check for Leaked Secrets
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source branch
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Check for secrets
              run: |
                  MSYS_NO_PATHCONV=1 docker run --volume .:/docs ghcr.io/gopro/opengopro-staging/gpdocchecker:docs secretchecker
                  ls -la
                  cat ./report.md >$GITHUB_STEP_SUMMARY
