name: Label issues
on:
    issues:
        types:
            - reopened
            - opened
jobs:
    label_issues:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - run: gh issue edit "$NUMBER" --add-label "$LABELS"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_REPO: ${{ github.repository }}
                  NUMBER: ${{ github.event.issue.number }}
                  LABELS: triage
