# Update the version, copyrights, make a commit, and tag the version

name: Make a Tagged Release

on:
    workflow_dispatch:
      inputs:
        version:
            description: 'version'
            required: true

jobs:
    version_and_tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source branch
              uses: actions/checkout@v2
              with:
                ref: main

            - name: Update version, copyrights, and make tag
              shell: bash
              run: |
                  git config core.fileMode false
                  make version VERSION=${{ github.event.inputs.version }}

            - name: Deploy to Github
              shell: bash
              run: |
                  git config core.fileMode false
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git commit -am "Set version to  $(VERSION) from github actions"
                  git push
                  git tag ${{ github.event.inputs.version }}
                  git push origin ${{ github.event.inputs.version }}
